### ISSUE TITLE
Icon path

### ISSUE THREAD

**Issue by triplus** [microelly2/Animation#15]
Small issue with icons (latest commit):

`/home/thomas/.FreeCAD/Mod/Animation/icons/collider.png`

**Comment by hyOzd** [comment]
I don't see any icons at all. Is this related?

**Comment by microelly2** [comment]
there is an error, I will fix it next days.

**Comment by microelly2** [comment]
path   for __dir__ changed cf9ba5d9f69c8c5db1e97aee868f1557e77a8123

**Comment by hyOzd** [comment]
Thanks, it works now.
