### ISSUE TITLE
Assembly2 controller failed

### ISSUE THREAD

**Issue by Nemesis81** [microelly2/Animation#16]
I got this message while trying to add an assembly2 controller : 
`'Running the Python command 'Anim_Assembly2Controller' failed:
Traceback (most recent call last):
  File "<string>", line 74, in Activated
  File "<string>", line 1, in <module>

'module' object has no attribute 'creanteAssembly2Controller'`

OS: Mac OS X
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.16.6510 (Git)
Build type: Release
Branch: (detached from 556ff4a)
Hash: 556ff4a4ac4f1dbfbdd9c6cc0e669a96f739465a
Python version: 2.7.11
Qt version: 4.8.7
Coin version: 3.1.3
OCC version: 6.8.0.oce-0.17

**Comment by microelly2** [comment]
It's a typing error in the InitGui.py, but I have to do some tests before I can merge the dev2 branch back to the main.
Will do it next days.
