### ISSUE TITLE
ER: Replace "Wheel of fortune" with slider

### ISSUE THREAD

**Issue by BPLRFE** [microelly2/Animation#21]
In Manager-dialogue i would prefer a slider and below the usual Buttons
> Play
> one Frame Forward
> one Frame back
> move to first Frame
> move to last Frame

Perhaps like the Simulation Player in the Robot workbench of FreeCAD ?
Thanks ...

**Comment by microelly2** [comment]
There is already such a functionality under the dialer by default.
If the dialer is active you can with the cursor-buttons  go one step forward and backward, with page up page down you can go 10 frames and with pos1 and end you can jump to the first, last frame
