### ISSUE TITLE
ER: Additional View for photographer

### ISSUE THREAD

**Issue by BPLRFE** [microelly2/Animation#23]
At the moment only fixed standard views could be chosen in the photographer.
Perhaps you could add a possibility to add also the actual camera position and orientation ?
At the moment the workaround would be to use Irfanview or something similar, make a screenshot of
every frame and put everything together into an animated gif using gif-x or something similar.

**Comment by microelly2** [comment]
Yes, these 22,23 makes sence. I will rethink the image interface for camera configuration, preview and image post processing.

**Comment by microelly2** [comment]
use the viewpoint node to configure camera position and direction
http://freecadbuch.de/doku.php?id=animation:viewpoint
