### ISSUE TITLE
animation workbench objects show error messages

### ISSUE THREAD

**Issue by bzb2** [microelly2/Animation#33]
Please refer to this post for details. https://forum.freecadweb.org/viewtopic.php?f=3&t=38494
When an animation workbench object (eg. Manager Dialog to create My_Manager node) is created, selecting Edit, Forward, Backward, Ping pong from the context menu would result in error messages at the FreeCAD  report view.
Same observation for other animation workbench objects as well.

**Comment by microelly2** [comment]
63f8d95a01a1d3d9f71606666d646f6e5a40a84d
