### ISSUE TITLE
placerdialog problem

### ISSUE THREAD

**Issue by Mumut18** [microelly2/Animation#34]
Hello,
I have the freecad version 0.18 16131 with windows 10.
When I click on the icon place dialog, nothing happens.
just a message:
![massage freecad](https://user-images.githubusercontent.com/55953272/65835137-d1b07700-e2e2-11e9-86e5-29ca24075475.jpg)

Running the python command 'Anim_Placer' failed: Traceback (most recent call last): "",line 74,in Actived File "", line 1, in name'reload'is not defined 

Thank you for your help

**Comment by microelly2** [comment]
solved with 63f8d95a01a1d3d9f71606666d646f6e5a40a84d

**Comment by Mumut18** [comment]
Good.
Run and test OK
Thank you
