### ISSUE TITLE
[enhancement] "back to original (default) position" button

### ISSUE THREAD

**Issue by herrdeh** [microelly2/Animation#9]
When trying to analyze a project, you will often move your components (rotate or linear), do adjustments at your components - and try again.

If "undo" is the only way to get back to the default position of your components, you will obviously lose your alterations at your parts as well. Therefore, the initial position of all components should be saved before starting movements - and restored on request.

**Comment by microelly2** [comment]
Yes, I will add a store and restore functiuon for the placement of all objects.

**Comment by microelly2** [comment]
the placer dialog  has a dialer which can move back and formward to any position on the animation path.
